# Generated by Django 5.1.7 on 2025-03-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_chaiverity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaiverity',
            name='price',
            field=models.TextField(default=''),
        ),
    ]
